begin;

create table public.usuarios (
    id_usuario bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    nombre text not null,
    rol text not null check (rol in ('administrador', 'vendedor')),
    activo boolean not null default true,
    fecha_creacion timestamptz not null default now()
);

create table public.clientes (
    id_cliente bigint generated by default as identity primary key,
    identificacion text unique not null,
    nombre text not null,
    apellido text not null,
    email text unique not null,
    telefono text,
    fecha_registro timestamptz not null default now()
);

create table public.ventas (
    id_venta bigint generated by default as identity primary key,
    id_cliente bigint not null
        references public.clientes(id_cliente) on delete restrict,
    id_usuario bigint not null
        references public.usuarios(id_usuario) on delete restrict,
    fecha_venta timestamptz not null default now(),
    subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
    impuestos numeric(12,2) not null default 0 check (impuestos >= 0),
    total numeric(12,2) not null default 0 check (total >= 0)
);

create table public.detalle_ventas (
    id_detalle bigint generated by default as identity primary key,
    id_venta bigint not null
        references public.ventas(id_venta) on delete restrict,
    id_producto bigint not null
        references public.productos(id_producto) on delete restrict,
    cantidad integer not null check (cantidad > 0),
    precio_unitario numeric(10,2) not null check (precio_unitario > 0),
    descuento numeric(10,2) not null default 0 check (descuento >= 0),
    check (descuento <= cantidad * precio_unitario)
);

create table public.historial_inventario (
    id_movimiento bigint generated by default as identity primary key,
    id_producto bigint not null
        references public.productos(id_producto) on delete restrict,
    id_usuario bigint not null
        references public.usuarios(id_usuario) on delete restrict,
    tipo_movimiento text not null
        check (tipo_movimiento in ('entrada', 'salida')),
    cantidad integer not null check (cantidad > 0),
    motivo text not null,
    fecha_movimiento timestamptz not null default now()
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'productos_precio_venta_positivo'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_precio_venta_positivo
            check (precio_venta > 0);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'productos_stock_actual_no_negativo'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_stock_actual_no_negativo
            check (stock_actual >= 0);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'productos_stock_minimo_no_negativo'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_stock_minimo_no_negativo
            check (stock_minimo >= 0);
    end if;
end;
$$;

create index ventas_id_cliente_idx on public.ventas(id_cliente);
create index ventas_id_usuario_idx on public.ventas(id_usuario);
create index detalle_ventas_id_venta_idx on public.detalle_ventas(id_venta);
create index detalle_ventas_id_producto_idx on public.detalle_ventas(id_producto);
create index historial_inventario_id_producto_idx
    on public.historial_inventario(id_producto);
create index historial_inventario_id_usuario_idx
    on public.historial_inventario(id_usuario);

create or replace function public.recalcular_totales_venta(p_id_venta bigint)
returns public.ventas
language plpgsql
set search_path = public
as $$
declare
    v_subtotal numeric(12,2);
    v_venta public.ventas%rowtype;
begin
    if not exists (
        select 1 from public.ventas where id_venta = p_id_venta
    ) then
        raise exception 'Venta no encontrada' using errcode = 'P0002';
    end if;

    select coalesce(
        sum(cantidad * precio_unitario - descuento),
        0
    )::numeric(12,2)
    into v_subtotal
    from public.detalle_ventas
    where id_venta = p_id_venta;

    update public.ventas
    set subtotal = v_subtotal,
        total = (v_subtotal + impuestos)::numeric(12,2)
    where id_venta = p_id_venta
    returning * into v_venta;

    return v_venta;
end;
$$;

create or replace function public.agregar_detalle_venta(
    p_id_venta bigint,
    p_id_producto bigint,
    p_cantidad integer,
    p_descuento numeric
)
returns public.detalle_ventas
language plpgsql
set search_path = public
as $$
declare
    v_id_usuario bigint;
    v_usuario_activo boolean;
    v_producto public.productos%rowtype;
    v_detalle public.detalle_ventas%rowtype;
    v_descuento numeric(10,2) := coalesce(p_descuento, 0);
begin
    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'La cantidad debe ser positiva' using errcode = 'P0001';
    end if;

    select id_usuario
    into v_id_usuario
    from public.ventas
    where id_venta = p_id_venta;

    if not found then
        raise exception 'Venta no encontrada' using errcode = 'P0002';
    end if;

    select activo
    into v_usuario_activo
    from public.usuarios
    where id_usuario = v_id_usuario;

    if not found then
        raise exception 'Usuario no encontrado' using errcode = 'P0002';
    end if;
    if not v_usuario_activo then
        raise exception 'El usuario esta inactivo' using errcode = 'P0001';
    end if;

    select *
    into v_producto
    from public.productos
    where id_producto = p_id_producto
      and estado = true
    for update;

    if not found then
        raise exception 'Producto no encontrado' using errcode = 'P0002';
    end if;
    if v_producto.stock_actual < p_cantidad then
        raise exception 'Stock insuficiente' using errcode = 'P0001';
    end if;
    if v_descuento < 0
       or v_descuento > p_cantidad * v_producto.precio_venta then
        raise exception 'El descuento no puede superar el importe de la linea'
            using errcode = 'P0001';
    end if;

    insert into public.detalle_ventas (
        id_venta,
        id_producto,
        cantidad,
        precio_unitario,
        descuento
    )
    values (
        p_id_venta,
        p_id_producto,
        p_cantidad,
        v_producto.precio_venta,
        v_descuento
    )
    returning * into v_detalle;

    update public.productos
    set stock_actual = stock_actual - p_cantidad
    where id_producto = p_id_producto;

    insert into public.historial_inventario (
        id_producto,
        id_usuario,
        tipo_movimiento,
        cantidad,
        motivo
    )
    values (
        p_id_producto,
        v_id_usuario,
        'salida',
        p_cantidad,
        format('Venta %s, detalle %s', p_id_venta, v_detalle.id_detalle)
    );

    perform public.recalcular_totales_venta(p_id_venta);
    return v_detalle;
end;
$$;

create or replace function public.actualizar_detalle_venta(
    p_id_detalle bigint,
    p_cantidad integer,
    p_descuento numeric
)
returns public.detalle_ventas
language plpgsql
set search_path = public
as $$
declare
    v_detalle public.detalle_ventas%rowtype;
    v_producto public.productos%rowtype;
    v_id_usuario bigint;
    v_usuario_activo boolean;
    v_nueva_cantidad integer;
    v_nuevo_descuento numeric(10,2);
    v_diferencia integer;
begin
    select *
    into v_detalle
    from public.detalle_ventas
    where id_detalle = p_id_detalle
    for update;

    if not found then
        raise exception 'Detalle de venta no encontrado' using errcode = 'P0002';
    end if;

    select id_usuario
    into v_id_usuario
    from public.ventas
    where id_venta = v_detalle.id_venta;

    if not found then
        raise exception 'Venta no encontrada' using errcode = 'P0002';
    end if;

    select activo
    into v_usuario_activo
    from public.usuarios
    where id_usuario = v_id_usuario;

    if not found then
        raise exception 'Usuario no encontrado' using errcode = 'P0002';
    end if;
    if not v_usuario_activo then
        raise exception 'El usuario esta inactivo' using errcode = 'P0001';
    end if;

    select *
    into v_producto
    from public.productos
    where id_producto = v_detalle.id_producto
    for update;

    if not found then
        raise exception 'Producto no encontrado' using errcode = 'P0002';
    end if;

    v_nueva_cantidad := coalesce(p_cantidad, v_detalle.cantidad);
    v_nuevo_descuento := coalesce(p_descuento, v_detalle.descuento);

    if v_nueva_cantidad <= 0 then
        raise exception 'La cantidad debe ser positiva' using errcode = 'P0001';
    end if;
    if v_nuevo_descuento < 0
       or v_nuevo_descuento > v_nueva_cantidad * v_detalle.precio_unitario then
        raise exception 'El descuento no puede superar el importe de la linea'
            using errcode = 'P0001';
    end if;

    v_diferencia := v_nueva_cantidad - v_detalle.cantidad;
    if v_diferencia > 0 and v_producto.stock_actual < v_diferencia then
        raise exception 'Stock insuficiente' using errcode = 'P0001';
    end if;

    if v_diferencia <> 0 then
        update public.productos
        set stock_actual = stock_actual - v_diferencia
        where id_producto = v_detalle.id_producto;

        insert into public.historial_inventario (
            id_producto,
            id_usuario,
            tipo_movimiento,
            cantidad,
            motivo
        )
        values (
            v_detalle.id_producto,
            v_id_usuario,
            case when v_diferencia > 0 then 'salida' else 'entrada' end,
            abs(v_diferencia),
            format('Ajuste del detalle de venta %s', p_id_detalle)
        );
    end if;

    update public.detalle_ventas
    set cantidad = v_nueva_cantidad,
        descuento = v_nuevo_descuento
    where id_detalle = p_id_detalle
    returning * into v_detalle;

    perform public.recalcular_totales_venta(v_detalle.id_venta);
    return v_detalle;
end;
$$;

create or replace function public.eliminar_detalle_venta(p_id_detalle bigint)
returns public.detalle_ventas
language plpgsql
set search_path = public
as $$
declare
    v_detalle public.detalle_ventas%rowtype;
    v_producto public.productos%rowtype;
    v_id_usuario bigint;
begin
    select *
    into v_detalle
    from public.detalle_ventas
    where id_detalle = p_id_detalle
    for update;

    if not found then
        raise exception 'Detalle de venta no encontrado' using errcode = 'P0002';
    end if;

    select id_usuario
    into v_id_usuario
    from public.ventas
    where id_venta = v_detalle.id_venta;

    if not found then
        raise exception 'Venta no encontrada' using errcode = 'P0002';
    end if;

    select *
    into v_producto
    from public.productos
    where id_producto = v_detalle.id_producto
    for update;

    if not found then
        raise exception 'Producto no encontrado' using errcode = 'P0002';
    end if;

    update public.productos
    set stock_actual = stock_actual + v_detalle.cantidad
    where id_producto = v_detalle.id_producto;

    insert into public.historial_inventario (
        id_producto,
        id_usuario,
        tipo_movimiento,
        cantidad,
        motivo
    )
    values (
        v_detalle.id_producto,
        v_id_usuario,
        'entrada',
        v_detalle.cantidad,
        format('Reversion del detalle de venta %s', p_id_detalle)
    );

    delete from public.detalle_ventas where id_detalle = p_id_detalle;
    perform public.recalcular_totales_venta(v_detalle.id_venta);
    return v_detalle;
end;
$$;

create or replace function public.registrar_movimiento_inventario(
    p_id_producto bigint,
    p_id_usuario bigint,
    p_tipo_movimiento text,
    p_cantidad integer,
    p_motivo text
)
returns public.historial_inventario
language plpgsql
set search_path = public
as $$
declare
    v_usuario_activo boolean;
    v_producto public.productos%rowtype;
    v_movimiento public.historial_inventario%rowtype;
begin
    if p_tipo_movimiento not in ('entrada', 'salida') then
        raise exception 'Tipo de movimiento invalido' using errcode = 'P0001';
    end if;
    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'La cantidad debe ser positiva' using errcode = 'P0001';
    end if;
    if nullif(btrim(p_motivo), '') is null then
        raise exception 'El motivo es obligatorio' using errcode = 'P0001';
    end if;

    select activo
    into v_usuario_activo
    from public.usuarios
    where id_usuario = p_id_usuario;

    if not found then
        raise exception 'Usuario no encontrado' using errcode = 'P0002';
    end if;
    if not v_usuario_activo then
        raise exception 'El usuario esta inactivo' using errcode = 'P0001';
    end if;

    select *
    into v_producto
    from public.productos
    where id_producto = p_id_producto
      and estado = true
    for update;

    if not found then
        raise exception 'Producto no encontrado' using errcode = 'P0002';
    end if;
    if p_tipo_movimiento = 'salida'
       and v_producto.stock_actual < p_cantidad then
        raise exception 'Stock insuficiente' using errcode = 'P0001';
    end if;

    update public.productos
    set stock_actual = case
        when p_tipo_movimiento = 'entrada' then stock_actual + p_cantidad
        else stock_actual - p_cantidad
    end
    where id_producto = p_id_producto;

    insert into public.historial_inventario (
        id_producto,
        id_usuario,
        tipo_movimiento,
        cantidad,
        motivo
    )
    values (
        p_id_producto,
        p_id_usuario,
        p_tipo_movimiento,
        p_cantidad,
        btrim(p_motivo)
    )
    returning * into v_movimiento;

    return v_movimiento;
end;
$$;

commit;
